// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using btvn.Data;

#nullable disable

namespace btvn.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("btvn.Models.Member", b =>
                {
                    b.Property<string>("MemberName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberName");

                    b.ToTable("tblMembers");

                    b.HasData(
                        new
                        {
                            MemberName = "a",
                            Email = "test@example.com",
                            Gender = true,
                            YearOfBirth = 2021
                        },
                        new
                        {
                            MemberName = "b",
                            Email = "testb@example.com",
                            Gender = true,
                            YearOfBirth = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
